version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  build:
    commands:
      - echo Building Docker images...
      - docker build -t eureka-server ./eureka-server
      - docker build -t intern-service ./intern-service
      - docker build -t training-service ./training-service
      - echo Pushing Docker images to ECR...
      - docker tag eureka-server:latest <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/eureka-server:latest
      - docker tag intern-service:latest <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/intern-service:latest
      - docker tag training-service:latest <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/training-service:latest
      - docker push 626635424541.dkr.ecr.us-west-2.amazonaws.com/eureka-server:latest
      - docker push 626635424541.dkr.ecr.us-west-2.amazonaws.com/intern-service:latest
      - docker push 626635424541.dkr.ecr.us-west-2.amazonaws.com/training-service:latest
  post_build:
    commands:
      - echo Build and push completed!
artifacts:
  files:
    - '**/*'
