# Eureka Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka
          image: snekha21/eureka-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  selector:
    app: eureka-server
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort

---
# Intern Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intern-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intern-service
  template:
    metadata:
      labels:
        app: intern-service
    spec:
      containers:
        - name: intern
          image: snekha21/intern-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8080/eureka/
              
---
apiVersion: v1
kind: Service
metadata:
  name: intern-service
spec:
  selector:
    app: intern-service
  ports:
    - port: 8081
      targetPort: 8000
      nodePort: 30082
  type: NodePort
---
# Training Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training-service
  template:
    metadata:
      labels:
        app: training-service
    spec:
      containers:
        - name: training
          image: snekha21/training-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8080/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: training-service
spec:
  selector:
    app: training-service
  ports:
    - port: 8082
      targetPort: 8001
      nodePort: 30081
  type: NodePort